== Quick Start

*Introduction:*

This introduction covers two aspects - making the microcontroller work with a bootloader, and, transferring the user program to the microcontroller.

{empty} +
{empty} +

_Making the microcontroller work with a bootloader_

You must transfer the bootloader firmware in your target microcontroller with an external programmer (i.e. Pickit programmers, etc...). This has to be done once.

Simply take the hex file and program with the selected programmer.

If the bootloader firmware for your target microcontroller  is not shown in the supported

isn't in "Tiny AVR/PIC Bootloader+" archive or you want to use a different Baud Rate and/or UART port, you must modify a firmware from a device close to yours (read "[Firmwares:] modify for xxxxx" web pages howto).
Connect PIC board to PC:
Now you can connect your AVR or PIC board to your PC (read the "Hardware Connections" web page).

Minimal connections are:
RX pin from PC -> TX pin on AVR or PIC.
TX pin from PC -> RX pin on AVR or PIC.
GND pin from PC -> GND pin on AVR or VSS pin on PIC.
for optionnal auto-reset: !RTS pin from PC -> !RESET pin on AVR or !MCLR pin on PIC
Note: for the bootloader to work properly, the AVR or PIC must be running (device powered and quartz connected (or internal oscillator correctly configured))!!!
Create your application ".hex" file:
Most of the time, you will develop your application firmware as usual, without having to modify something: neither your code, nor the linker script, nor remap reset/interrupts vectors to new locations, etc.

The "Tested Compilers: xxxxx" web page lists tested compilers for different AVR / PIC families with eventual tips to get your code working with "Tiny AVR/PIC Bootloader+".

{empty} +
{empty} +

_Transferring the  user program to the microcontroller:_

The easiest way to use "Tiny AVR/PIC Bootloader+" is to leave all options as default and only change the PC's COM (select the one connected to the AVR or PIC board) and the Baud Rate (select it depending of the bootloader firmware configuration, see "[Firmwares:] modify for xxxxx" web pages).
Check list:
- the AVR or PIC was programmed with the right bootloader firmware?
- the AVR or PIC is correctly connected to the PC?
- the AVR or PIC is powered?
- the right COM port is selected in "Tiny AVR/PIC Bootloader+"?
- the right Baud Rate is selected in "Tiny AVR/PIC Bootloader+"?
If previous checks are OK, then click on the [Check Device] button:
They are two possibilities:
"Found: xxxxx" is shown in the message tab. Everything is OK, then read "Transfert file" below.
"Error: No Device detected!!!" is shown in the message tab. It means that optionnal software reset isn't used (!RTS pin from PC isn't connected to !MCLR pin on PIC (see "Hardware Connections" web page)).  Then click the [Check Device] button again and when "Check Device..." is shown in the message tab, manually reset the AVR or PIC device (it must be done before "Error: No Device detected!!!" appears, you have ~5 seconds):
"Found: xxxxx" is shown in the message tab. Everything is OK, then read "Transfert file" below.
"Error: No Device detected!!!" is shown in the message tab. Then you have a problem... Double check everything! If it still doesn't work you can ask for help in the forum.
Transfert file:
Click on the [Browse] button and select your application's ".hex" file, then click on [Write Flash]. After a few messages, you should have "Transfert successfull :-)".
Well done!
